import type { InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const API = 'https://pokeapi.co/api/v2/'
const LIMIT = 100

const Home = ({ pokemons, count, limit }: InferGetStaticPropsType<typeof getStaticProps>) => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          showing {limit}  of {count} pokemons
        </h1>
        <ul>
          {pokemons.map((char) => (
            <li key={char.url}>
              {char.name}
            </li>
          ))}
        </ul>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const resp = await fetch(`${API}pokemon?limit=${LIMIT}`)
  const {count, results}: {
    count: number
    results: {
      name: string
      url: string
    }[]
  } = await resp.json()
  return {
    props: {
      limit: LIMIT,
      count,
      pokemons: results
    }
  }
}


export default Home