import type { InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import styles from 'styles/Home.module.css'
import Link from 'next/link'
import { fetchPkmList } from 'utils/fetch-pkm'

const Home = ({
  pokemons,
  count,
  limit,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          showing {limit} of {count} pokemons
        </h1>
        <ul>
          {pokemons.map(({ name, url }) => (
            <li key={url}>
              <Link href={`/${name}`}>
                <a>{name}</a>
              </Link>
            </li>
          ))}
        </ul>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const { limit, count, pokemons } = await fetchPkmList()

  return {
    props: {
      limit,
      count,
      pokemons,
    },
  }
}

export default Home
